Tidy up kind workflow

diff --git a/.github/workflows/ci-kind.yml b/.github/workflows/ci-kind.yml
--- a/.github/workflows/ci-kind.yml
+++ b/.github/workflows/ci-kind.yml
@@ -48,8 +48,10 @@ jobs:
 
         sleep 60
 
-        kubectl get pod -A
-        kubectl get svc -A
+        curl -o /dev/null -s -w "%{http_code}\n" http://localhost/home
 
-        curl localhost/home
+        if [[ "$status_code" -ne 200 ]] ; then
+          echo "Error: HTTP status code not 200 ($status_code)"
+          exit 1
+        fi
     
